<template>
  <div class="space-y-6">
    <!-- Header -->
    <div class="text-center space-y-4">
      <h1 class="text-3xl font-bold text-primary">{{ $t('community.title') }}</h1>
      <p class="text-secondary max-w-2xl mx-auto">
        Explore sentences generated by learners around the world and discover new ways to use English words.
      </p>
    </div>

    <!-- Filters and Controls -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
      <div class="flex items-center space-x-4">
        <label for="sortBy" class="text-sm font-medium text-primary">
          {{ $t('community.sortBy') }}:
        </label>
        <select
          id="sortBy"
          v-model="currentSortBy"
          @change="handleSortChange"
          class="input py-1 px-2 text-sm"
        >
          <option value="recent">{{ $t('community.recent') }}</option>
          <option value="liked">{{ $t('community.liked') }}</option>
          <option value="trending">{{ $t('community.trending') }}</option>
        </select>
      </div>

      <div class="flex items-center space-x-2">
        <button
          @click="refreshGenerations"
          :disabled="generationsStore.loading"
          class="btn btn-ghost btn-sm"
        >
          <ArrowPathIcon class="w-4 h-4 mr-1" :class="{ 'animate-spin': generationsStore.loading }" />
          {{ $t('common.refresh') }}
        </button>
        
        <router-link
          v-if="authStore.isAuthenticated"
          to="/generate"
          class="btn btn-primary btn-sm"
        >
          <SparklesIcon class="w-4 h-4 mr-1" />
          Create Your Own
        </router-link>
      </div>
    </div>

    <!-- Statistics -->
    <div class="grid grid-cols-1 sm:grid-cols-3 gap-6">
      <div class="card text-center">
        <div class="card-body">
          <div class="text-3xl font-bold text-blue-600 mb-2">{{ stats.totalGenerations }}</div>
          <p class="text-sm text-secondary">Total Generations</p>
        </div>
      </div>
      <div class="card text-center">
        <div class="card-body">
          <div class="text-3xl font-bold text-green-600 mb-2">{{ stats.totalWords }}</div>
          <p class="text-sm text-secondary">Words Used</p>
        </div>
      </div>
      <div class="card text-center">
        <div class="card-body">
          <div class="text-3xl font-bold text-purple-600 mb-2">{{ stats.totalLikes }}</div>
          <p class="text-sm text-secondary">Total Likes</p>
        </div>
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="generationsStore.loading && generationsStore.publicGenerations.length === 0" class="text-center py-12">
      <div class="spinner-lg mx-auto mb-4"></div>
      <p class="text-secondary">{{ $t('common.loading') }}...</p>
    </div>

    <!-- Empty State -->
    <div v-else-if="generationsStore.publicGenerations.length === 0" class="text-center py-12">
      <UsersIcon class="w-16 h-16 text-gray-400 mx-auto mb-4" />
      <h3 class="text-lg font-medium text-primary mb-2">{{ $t('community.noGenerations') }}</h3>
      <p class="text-secondary mb-4">Be the first to share a generation with the community!</p>
      <router-link
        v-if="authStore.isAuthenticated"
        to="/generate"
        class="btn btn-primary"
      >
        <SparklesIcon class="w-4 h-4 mr-2" />
        Create Generation
      </router-link>
      <router-link
        v-else
        to="/register"
        class="btn btn-primary"
      >
        Join Community
      </router-link>
    </div>

    <!-- Generations Feed -->
    <div v-else class="space-y-6">
      <GenerationCard
        v-for="generation in generationsStore.publicGenerations"
        :key="generation._id"
        :generation="generation"
        :show-actions="authStore.isAuthenticated"
      />

      <!-- Load More Button -->
      <div v-if="generationsStore.publicPagination.hasNext" class="text-center">
        <button
          @click="loadMore"
          :disabled="generationsStore.loading"
          class="btn btn-secondary"
        >
          <div v-if="generationsStore.loading" class="spinner mr-2"></div>
          {{ $t('community.loadMore') }}
        </button>
      </div>

      <!-- End of Feed -->
      <div v-else-if="generationsStore.publicGenerations.length > 0" class="text-center py-8">
        <p class="text-secondary">You've reached the end of the feed!</p>
        <button
          @click="refreshGenerations"
          class="btn btn-ghost mt-2"
        >
          {{ $t('common.refresh') }}
        </button>
      </div>
    </div>

    <!-- Call to Action for Guest Users -->
    <div v-if="!authStore.isAuthenticated" class="text-center py-12 bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 rounded-2xl">
      <div class="space-y-4">
        <h3 class="text-2xl font-bold">Join Our Learning Community</h3>
        <p class="text-secondary max-w-2xl mx-auto">
          Create your own word collections, generate AI-powered sentences, and share your learning journey with others.
        </p>
        <div class="flex flex-col sm:flex-row gap-3 justify-center">
          <router-link to="/register" class="btn btn-primary">
            Get Started Free
          </router-link>
          <router-link to="/login" class="btn btn-secondary">
            Sign In
          </router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { 
  SparklesIcon, 
  UsersIcon, 
  ArrowPathIcon 
} from '@heroicons/vue/24/outline'
import { useGenerationsStore } from '../stores/generations'
import { useAuthStore } from '../stores/auth'
import GenerationCard from '../components/GenerationCard.vue'

const generationsStore = useGenerationsStore()
const authStore = useAuthStore()

const currentSortBy = ref('recent')

// Mock statistics - in a real app, this would come from an API
const stats = ref({
  totalGenerations: 1247,
  totalWords: 8932,
  totalLikes: 3456
})

onMounted(async () => {
  await loadGenerations()
})

const loadGenerations = async () => {
  await generationsStore.fetchPublicGenerations(1, currentSortBy.value)
}

const handleSortChange = async () => {
  await generationsStore.refreshPublicGenerations(currentSortBy.value)
}

const refreshGenerations = async () => {
  await generationsStore.refreshPublicGenerations(currentSortBy.value)
}

const loadMore = async () => {
  await generationsStore.loadMorePublicGenerations(currentSortBy.value)
}
</script> 